### PR TITLE
Split library and binary

### PR DESCRIPTION
**Pull request by federicomenaquintero**
This separates the library sources from the idchoppers binary using a Cargo workspace.

This also adds an `InputBuffer`, which can slurp the contents of stdin or memory-map a file, and present a `&[u8]` for either of them.

### CODE REVIEW

**Comment by eevee** [comment]
Sorry for the wait; I've had a… turbulent summer.

I don't know how Cargo workspaces work but this _sounds_ reasonable  :)

**Comment by eevee** [comment]
Oh, out of curiosity, do you know why `Mmap.map()` is `unsafe`?  I don't see any mention of it in the docs.

**Comment by federicomenaquintero** [comment]
> Oh, out of curiosity, do you know why Mmap.map() is unsafe

What I can glean from [this](https://github.com/danburkert/memmap-rs/issues/25) is that Mmap gives you a `&[u8]`, which Rust would have you believe is immutable — but if e.g. some other process writes to the file, then the mmap will change when read again.  I think they want you to be aware that this could happen, or that you should limit it with file locks / whatever.

I'll file a bug about clarifying this in the docs.

**Comment by federicomenaquintero** [comment]
Filed https://github.com/danburkert/memmap-rs/issues/70 about clarifying unsafety in file-backed maps.

**Comment by 1011X** [comment]
Why use `memmap`? Seems like using [`std::io::BufReader`](https://doc.rust-lang.org/std/io/struct.BufReader.html) would be simpler and with less dependencies.

**Pull request merged**
